---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url: 
sections:
- type: directory
  path: content/sections
  label: Content Sections
  create: all
  match: "**/*"
  templates:
  - section-grid
- type: directory
  path: content/blocks/content-blocks
  label: Content Blocks
  create: all
  match: "**/*"
  templates:
  - block-title
  - block-text
  - block-youtube-embed
  - block-image-with-caption
- type: directory
  path: content/blocks/members
  label: Members
  create: all
  match: "**/*"
  templates:
  - team-member
- type: directory
  path: content/data
  label: Data
  create: all
  match: "**/*"
  new_doc_ext: json
- type: directory
  path: content/blocks/roles
  label: Roles
  create: all
  match: "**/*"
  templates:
  - role-template
- type: directory
  path: content/pages
  label: Pages
  create: all
  match: "**/*"
- type: directory
  path: content/pages/regions
  label: Regions
  create: all
  match: "**/*"
  templates:
  - region-page
  - sub-region-page
  - linkslist
  - update
- type: directory
  path: content/blocks/activities
  label: Activities
  create: all
  match: "**/*"
  templates:
  - activity-template
- type: directory
  path: content/blocks/shipments
  label: Shipment Photos
  create: all
  match: "**/*"
  templates:
  - media-asset
- type: document
  path: content/site-settings.json
  label: Site Settings
- type: directory
  path: content/blocks/fundraisers
  label: Fundraiser
  create: all
  match: "**/*"
  templates:
  - fundraiser
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - DISABLE_CODESEE_INSTRUMENTATION=1
  preview_output_directory: public
  install_dependencies_command: yarn install
  preview_docker_image: node:16
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn forestry:preview
